name: Deploy to Hetzner Server

# Trigger deployment on push to the main branch
on:
  push:
    branches:
      - main
      - '**'  # Run on all branches to test before merging.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install pytest pytest-cov

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Start Flask server
      run: |
        python main.py &
        # Wait for server to be ready
        for i in {1..30}; do
          if curl -s http://127.0.0.1:5000 > /dev/null; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for server... ($i)"
          sleep 1
        done

    - name: Run unit tests
      run: |
        pytest --cov=main tests/

    - name: Run E2E tests
      run: |
        pytest tests/e2e -v --capture=no

  deploy:
    needs: test  # Deploy only if tests pass
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Hetzner server
      run: >-
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e  # Exit on error

          echo "Starting deployment..."

          # Step 1: Backup current deployment
          if [ -d "$HOME/eat-me" ]; then
            echo "Backing up current deployment..."
            rm -rf "$HOME/myapp_backup" || true
            cp -r "$HOME/eat-me" "$HOME/myapp_backup"
          else
            echo "No current deployment found to back up."
          fi

          # Step 2: Deploy new code
          echo "Deploying new code..."
          cd "$HOME/eat-me" || exit 1
          git reset --hard HEAD || exit 1
          git pull origin main || exit 1

          # Step 3: Restart services
          echo "Restarting services..."
          sudo systemctl restart nginx || exit 1
          sudo systemctl restart eat-me.service || exit 1
        EOF
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}

    - name: Check deployment status
      if: ${{ success() }}
      run: echo "Deployment successful!"
      
    - name: Rollback on failure
      if: ${{ failure() }}
      run: >-
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e  # Exit on error

          echo "Rollback initiated due to deployment failure..."

          if [ -d "$HOME/myapp_backup" ]; then
            echo "Rolling back to the previous version..."
            rm -rf "$HOME/eat-me" || true
            mv "$HOME/myapp_backup" "$HOME/eat-me"
            sudo systemctl restart nginx || exit 1
            sudo systemctl restart eat-me.service || exit 1
          else
            echo "No backup available for rollback!"
          fi
        EOF
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
